# Copyright (c) 2025. All rights reserved.
# project.py
# This file was generated by NuActionGUI with empty function implementations.
# The developer has already provided the function implementations.
# Please do not modify the function implementations.


from flask import render_template, redirect, url_for
from flask_user import current_user
from dtm import db, Event, Category, Person, Role, Ad, Log, Invite
from auxiliary import recommend_events, get_personalize_ad, send_advertisement_to_user, get_candidates
import time


def main(request):
    user = current_user
    recommended = recommend_events({'user': user}) if user.is_authenticated else []
    return render_template('main.html', user=user, recommended_events=recommended)


def users(request):
    users = Person.query.all()
    return render_template('users.html', users=users)


def user(request):
    user = Person.query.get(request.args["id"])
    roles = Role.getAuthenticatedRoles()
    return render_template('user.html', user=user, roles=roles)


def profile(request):
    user = current_user
    ad = get_personalize_ad({'user': user}) if user.is_authenticated else None
    return render_template('profile.html', user=user, ad=ad)


def update_user(request):
    user = Person.query.get(request.form["id"])
    # Updating user's name field if it has changed
    if request.form["name"] and user.name != request.form["name"]:
        user.name = request.form["name"]
    # Updating user's surname field if it has changed
    if request.form["surname"] and user.surname != request.form["surname"]:
        user.surname = request.form["surname"]
    # Updating user's email field if it has changed
    if request.form["email"] and user.email != request.form["email"]:
        user.email = request.form["email"]
    # Updating user's gender field if it has changed
    new_gender = request.form["gender"]
    if new_gender == "":
        new_gender = None
    if new_gender != user.gender:
        user.gender = new_gender
    # Updating user's role if it has changed
    if user.role.name != request.form["role"]:
        user.role = Role.query.filter_by(name=request.form["role"]).first()
    db.session.commit()
    return redirect(url_for('user',id=request.form["id"]))


def join(request):
    event = Event.query.get(request.args["id"])
    if current_user.id not in [p.id for p in event.requesters]:
        p = Person.query.get(current_user.id)
        event.requesters.append(p)
        db.session.commit()
    return redirect(url_for('events'))


def leave(request):
    event = Event.query.get(request.args["id"])
    if current_user.id in [p.id for p in event.attendants]:
        p = Person.query.get(current_user.id)
        event.attendants.remove(p)
        db.session.commit()
    return redirect(url_for('profile'))


def add_moderator(request):
    user = Person.query.get(request.args["id"])
    category = Category.query.get(request.args["c"])
    if user not in category.moderators:
        category.moderators.append(user)
        db.session.commit()
    return redirect(url_for('edit_category',id=request.args["c"]))


def remove_moderator(request):
    user = Person.query.get(request.args["id"])
    category = Category.query.get(request.args["c"])
    if user in category.moderators:
        category.moderators.remove(user)
        db.session.commit()
    return redirect(url_for('edit_category',id=request.args["c"]))


def subscribe(request):
    category = Category.query.get(request.args["id"])
    if category not in current_user.subscriptions:
         current_user.subscriptions.append(category)
         db.session.commit()
    return redirect(url_for('categories'))


def unsubscribe(request):
    category = Category.query.get(request.args["id"])
    if category in current_user.subscriptions:
         current_user.subscriptions.remove(category)
         db.session.commit()
    return redirect(url_for('profile'))


def events(request):
    events = Event.query.all()
    categories = Category.query.all()
    return render_template('events.html', events=events, categories=categories)


def create_event(request):
    event = Event()
    event.owner = current_user
    event.managedBy.append(current_user)
    event.attendants.append(current_user)
    event.title = request.form["title"]
    event.description = request.form["description"]
    categories = request.form.getlist("categories")
    for cid in categories:
        c = Category.query.get(cid)
        event.categories.append(c)
    db.session.add(event)
    db.session.commit()
    return redirect(url_for('events'))


def view_event(request):
    event=Event.query.get(request.args["id"])
    # Create a log entry for viewing the event
    log = Log()
    log.timestamp = int(time.time())
    log.user = current_user if current_user.is_authenticated else None
    log.event = event
    db.session.add(log)
    db.session.commit()
    return render_template('view_event.html', event=event)


def edit_event(request):
    event = Event.query.get(request.args["id"])
    categories = Category.query.all()
    return render_template('edit_event.html', event=event, categories=categories)


def update_event(request):
    event = Event.query.get(request.form["id"])
    # Updating event's title if it has changed
    if event.title != request.form["title"]:
        event.title = request.form["title"]
    # Updating event's description if it has changed
    if event.description != request.form["description"]:
        event.description = request.form["description"]
    # Updating event's categories if they have changed
    new_categories = [int(id) for id in request.form.getlist("categories")] 
    current_categories = [c.id for c in event.categories]
    if set(current_categories) != set(new_categories):
        ids_to_remove = set(current_categories) - set(new_categories)
        ids_to_add = set(new_categories) - set(current_categories)
        # Only remove the deleted ones
        for cid in ids_to_remove:
            c = Category.query.get(cid)
            event.categories.remove(c)
        # and add the new ones
        for cid in ids_to_add:
            c = Category.query.get(cid)
            event.categories.append(c)
    db.session.commit()
    return redirect(url_for('edit_event', id=request.form["id"]))


def manage_event(request):
    event = Event.query.get(request.args["id"])
    all_users = Person.query.all()
    invitees = list([i.invitee.id for i in event.invitations])
    attendants = list([p.id for p in event.attendants])
    requesters = list([p.id for p in event.requesters])
    users = []
    for u in all_users:
        if u.id not in invitees and u.id not in attendants and u.id not in requesters:
            users.append(u)
    return render_template('manage_event.html', event=event, users=users)


def remove_category(request):
    event = Event.query.get(request.args["id"])
    category = Category.query.get(request.args["c"])
    if event in category.events:
        category.events.remove(event)
        db.session.commit()
    return redirect(url_for('view_category',id=request.args["c"]))


def promote_manager(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    if user not in event.managedBy:
        event.managedBy.append(user)
        db.session.commit()  
    return redirect(url_for('manage_event',id=request.args["e"]))


def demote_manager(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    if user in event.managedBy:
        event.managedBy.remove(user)
        db.session.commit()
    return redirect(url_for('manage_event',id=request.args["e"]))


def remove_attendee(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    if user in event.attendants:
        event.attendants.remove(user)
        db.session.commit()
    return redirect(url_for('manage_event',id=request.args["e"]))


def accept_request(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    if user not in event.attendants:
        event.attendants.append(user)
    event.requesters.remove(user)
    db.session.commit()
    return redirect(url_for('manage_event',id=request.args["e"]))


def reject_request(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    event.requesters.remove(user)
    db.session.commit()
    return redirect(url_for('manage_event',id=request.args["e"]))


def categories(request):
    categories = Category.query.all()
    return render_template('categories.html', categories=categories)


def create_category(request):    
    category = Category()
    category.name = request.form["name"]
    db.session.add(category)
    db.session.commit()
    return redirect(url_for('categories'))


def view_category(request):
    category = Category.query.get(request.args["id"])
    return render_template('view_category.html', category=category)


def edit_category(request):
    category = Category.query.get(request.args["id"])
    candidates = get_candidates({'cat': category})
    return render_template('edit_category.html', category=category, candidates=candidates)


def update_category(request):
    category = Category.query.get(request.form["id"])
    # Updating category's name if it has changed
    if category.name != request.form["name"]:
        category.name = request.form["name"]
    db.session.commit()
    return redirect(url_for('edit_category',id=request.form["id"]))


def ads(request):  
    ads = Ad.query.all()
    return render_template('ads.html', ads=ads)


def remove_ad(request):
    ad = Ad.query.get(request.args["id"])
    db.session.delete(ad)
    db.session.commit()
    return redirect(url_for('ads'))


def create_ad(request):
    ad = Ad()
    ad.content = request.form["content"]
    db.session.add(ad)
    db.session.commit()
    return redirect(url_for('ads'))


def send_mass_advertisement(request):
    category = Category.query.get(request.args["id"])
    for p in category.subscribers:
        send_advertisement_to_user({'user': p})
    return redirect(url_for('categories'))


def analyze(request):
    event = Event.query.get(request.args["id"])
    gender_counts = {"male": 0, "female": 0, "unknown": 0}
    for p in event.attendants:
        gender = p.gender if p.gender in gender_counts else "unknown"
        gender_counts[gender] += 1    
    return render_template('analyze.html', event=event, male=gender_counts['male'], female=gender_counts['female'], unknown=gender_counts['unknown'])


def logs(request):
    logs = Log.query.all()
    def format_timestamp(timestamp):
        try:
            return time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(timestamp))
        except:
            return timestamp
    return render_template('logs.html', logs=logs, format_timestamp=format_timestamp)

# New code for phase 3 - ChangeRequest code

def personalized_stats(request):
    user = current_user
    return render_template('personalized_stats.html', user=user)


def send_invite(request):
    user = Person.query.get(request.args["id"])
    event = Event.query.get(request.args["e"])
    invite = Invite()
    invite.event = event
    invite.invitedBy = current_user
    invite.invitee = user
    db.session.commit()
    return redirect(url_for('manage_event', id=request.args["e"]))


def accept_invitation(request):
    invite = Invite.query.get(request.args["id"])
    event = invite.event
    user = invite.invitee
    event.attendants.append(user)
    db.session.delete(invite)
    db.session.commit()
    return redirect(url_for('profile'))


def decline_invitation(request):
    invite = Invite.query.get(request.args["id"])
    db.session.delete(invite)
    db.session.commit()
    return redirect(url_for('profile'))
