# Copyright (c) 2025. All rights reserved.
# project_aux.py
# This file was generated by NuActionGUI with empty function implementations.
# The developer has already provided the function implementations.
# Please do not modify the function implementations.


import hashlib
import random
from dtm import Role, Person, Ad, Event
import sys


def recommend_events(args):
    user = args['user']
    subscribed_event_ids = []
    for category in user.subscriptions:
        for event in category.events:
            subscribed_event_ids.append(event.id)
    viewing_event_ids = []
    for log in user.logs:
        event = log.event
        viewing_event_ids.append(event.id)
    recommend_event_ids = list(set(subscribed_event_ids + viewing_event_ids) - set([event.id for event in user.attends]))
    recommend_events = [
        Event.query.get(id) for id in recommend_event_ids
    ]
    return recommend_events

def get_personalize_ad(args):
    user = args['user']
    seed_string = f"{user.id}{user.name}{user.gender}"
    seed_value = int(hashlib.sha256(seed_string.encode()).hexdigest(), 16)
    random.seed(seed_value)
    ads = Ad.query.all()
    if len(ads) == 0:
        return None
    else:
        return ads[random.randint(1, len(ads)) - 1]


def send_advertisement_to_user(args):
    user = args['user']
    if user.email:
        print(f'A generic advertisement was sent to {user.name} at email: {user.email}.', file=sys.stderr)


def get_candidates(args):
    cat = args['cat']
    all_ids = [m.id for m in Person.query.all() if Role.MODERATOR == m.role]
    mod_ids = [m.id for m in cat.moderators]
    candidate_ids = list(set(all_ids) - set(mod_ids)) 
    return [Person.query.get(id) for id in candidate_ids]